name: product-catalog-ci
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
        
        - name: build
          run: |
            cd src/product-catalog
            go mod download
            go build -o product-catalog src/product-catalog/main.go
        
        - name: run unittests
          run: go test ./src/product-catalog/...
    code-quality:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
    
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.56.2
            working-directory: ./src/product-catalog
    docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/checkout@v4
         
        - name: Install Docker
          uses: docker/setup-buildx-action@v1

        - name: Docker login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Docker build & push
          uses: docker/build-push-action@v6
          with:
            context: src/product-catalog
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
    Update-K8s:
        runs-on: ubuntu-latest
        needs: docker
        steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Update Tag in k8s deployment manifest
          run: |
            sed -i "s/image:.*/image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}/g" kubernetes/product-catalog/deploy.yaml
            cat kubernetes/product-catalog/deploy.yaml
        - name: Commit and Push the changes
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add kubernetes/product-catalog/deploy.yaml
            git commit -m "Update product-catalog image tag to ${{ github.run_id }}"
            git push
